### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by Mavrick007** [astravaganza/broadcom_lvl1#1]
i cant get this to work with amazon or netflix tool please help thanks

**Comment by UniversalDecryptOfficial** [comment]
It's blacklisted on Amazon.

**Comment by Mavrick007** [comment]
> It's blacklisted on Amazon.

what about netflix and is this a l1 cdm?

**Comment by astravaganza** [comment]
> > It's blacklisted on Amazon.
> 
> what about netflix and is this a l1 cdm?

Blocked on netflix and yes its LEVEL_1
